version: "3"

# docker-composes works with services.
services:
    opprett-avtale-api:
        # build from this directory
        build: ./api
        command: mvn exec
        volumes:
            - ./api:/usr/src/app
        ports:
            - 30002:30002

    opprett-avtale-client:
        build: ./client
        command: npm start
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 420:420
