version: "3"

# docker-composes works with services.
services:
    # api:
    #     # build from this directory
    #     build: ./api
    #     command: mvn exec:java
    #     volumes:
    #         - ./api:/opt/app
    #     ports:
    #         - 4090:4090

    client:
        build: ./client
        command: npm start
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
